### ISSUE TITLE
Plot transitions are a little jumpy

### ISSUE THREAD

**Issue by tmelliott** [iNZightVIT/iNZightModules#28]
Couple of suggestions to make transitioning between plots nicer:

1. Remove the "Please wait ... Loading" text overlaying the plot. Either set the cursor [to a loading cursor](https://stackoverflow.com/questions/17309532/how-can-i-change-the-shape-mouse-cursor-in-gwidgets-rgtk2), or put the message at the bottom of the plot (so it's not in the way).

2. Place legends underneath (by default? with an option to have legends on the right, or not at all). Changes are the map will be constrained horizontally, not vertically, so this way the plots will be the same size and again transitions between plots will be easier to see. Could even force the legend box (underneath) to remain a constant size (i.e., 5, 10% of the full plot height) using `gridExtra::grid.arrange()`. Stepping through variables (in particular time) will make it easier to see the data changing, rather than the graph.

3. Timer on the time slider? [Something like this](https://github.com/iNZightVIT/iNZight/blob/master/R/iNZPlotModWin.R#L1486-L1491)

**Comment by daniel-barnett** [comment]
Some things I was thinking about the legends:
1) bottom, like you said (the reason why it's on the right at the moment is because the text starts overlapping which I'll need to fix)

2) if we're looking at multiple variables that are all proportions, put a single legend at the bottom as it looks fairly ridiculous with, say, 9 legends of 0.0 - 1.0

**Comment by tmelliott** [comment]
One thing the previous version had was you could optionally add text labels to each 'country' - either the name, or more usefully the value of the variable. Legends are only useful if you care about the values; the main point of interest is how various values differ. Users could have choice between showing the legend, or placing the value labels directly onto the graph.

**Comment by daniel-barnett** [comment]
That comes from the region labels checkbox currently, but needs a few more tweaks such as rounding (7dp everywhere doesn't look great). General toggling of the legend could be useful here - "bottom", "right", "none" combobox maybe?

**Comment by tmelliott** [comment]
Closing because it's old - @daniel-barnett if there's anything useful etc just open a new issue :+1:
