### ISSUE TITLE
Colour range for multiple variables when animating

### ISSUE THREAD

**Issue by daniel-barnett** [iNZightVIT/iNZightModules#29]
Currently takes the min/max of either the first variable or all plotted variables.

So if one variable ranges from 0-1 and the other ranges from 1000-1,000,000 we can't see anything useful from the first map. 

Just have to do something more sensible about the scale limits.

**Comment by tmelliott** [comment]
Still relevant @daniel-barnett?

**Comment by daniel-barnett** [comment]
This is fixed IIRC

**Comment by tmelliott** [comment]
Let's just call it fixed then!
