### ISSUE TITLE
"Transparency" vs "Opacity"

### ISSUE THREAD

**Issue by tmelliott** [iNZightVIT/iNZightModules#31]
In the Maps UI for sparklines (may be elsewhere, haven't checked), you have "Transparency of map" with values in [0,1]. 

Technically, transparency = 0 == opacity = 1 (completely visible), whilst transparency = 1 == opacity = 0 (completely hidden). 

Your slider is around the wrong way: the default should be 0, and completely show the map, and dragging it to the right towards 1 should incrementally make the map invisible (this is how it works in Add to Plot).

**Comment by daniel-barnett** [comment]
Fixed in https://github.com/iNZightVIT/iNZightModules/commit/e15825f00c5b5eee3a79e9eed8b6f2f1bdd654c4
